name: CI

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - bugfix/*
  pull_request:
    branches:
      - main
      - develop
      - feature/*
      - bugfix/*

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: symfony_test
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: pdo, pdo_pgsql
          tools: composer

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Run database migrations
        run: php bin/console doctrine:migrations:migrate --no-interaction

      - name: Run tests
        run: php bin/phpunit